const items = [
    "@hsyn._art.jpg",
    "@hsyn._art (1).jpg",
    "@hsyn._art (2).jpg",
    "@hsyn._art (3).jpg",
    "@hsyn._art (4).jpg",
    "@hsyn._art (5).jpg",
    "@hsyn._art (6).jpg",
    "@hsyn._art (7).jpg",
    "@hsyn._art (8).jpg",
    "@hsyn._art (9).jpg",
    "@hsyn._art (10).jpg",
    "@hsyn._art (11).jpg",
    "@hsyn._art (12).jpg",
    "@hsyn._art (13).jpg",
    "@hsyn._art (14).jpg",
    "@hsyn._art (15).jpg",
    "@hsyn._art (16).jpg",
    "@hsyn._art (17).jpg",
    "@hsyn._art (18).jpg",
    "@hsyn._art (19).jpg",
    "@hsyn._art (20).jpg",
    "@hsyn._art (21).jpg",
    "@hsyn._art (22).jpg",
    "@hsyn._art (23).jpg",
    "@hsyn._art (24).jpg",
    "@hsyn._art (25).jpg",
    "@hsyn._art (26).jpg",
    "@hsyn._art (27).jpg",
    "@hsyn._art (28).jpg",
    "@hsyn._art (29).jpg",
    "@hsyn._art (30).jpg"
];

export default items;